name: Build and push to ecr

on:
  push:
    branches: ["main"]
    paths:
      - app/**

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      APP_NAME: gitops-app
      IMAGE_TAG: ${{ github.run_number }}
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/gitops-app:${{ github.run_number }}

    steps:
      - name: checkout git
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker image
        run: |
          echo "Building Docker image with tag $IMAGE_NAME"
          docker build -t $IMAGE_NAME -f app/Containerfile  app/

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub"
          docker push $IMAGE_NAME
